def stage_1():
    print("  -----")
    print("  |   |")
    print("      |")
    print("      |")
    print("      |")
    print("      |")
    print("      |")
    print("      |")
    print("      |")
    print("      |")
    print("-------")

def stage_2():
    print("  -----")
    print("  |   |")
    print("  O   |")
    print("      |")
    print("      |")
    print("      |")
    print("      |")
    print("      |")
    print("      |")
    print("      |")
    print("-------")

def stage_3():
    print("  -----")
    print("  |   |")
    print("  O   |")
    print(" ---  |")
    print("/ | \ |")
    print("      |")
    print("      |")
    print("      |")
    print("      |")
    print("      |")
    print("-------")

def stage_4():
    print("  -----")
    print("  |   |")
    print("  O   |")
    print(" ---  |")
    print("/ | \ |")
    print("  |   |")
    print("      |")
    print("      |")
    print("      |")
    print("      |")
    print("-------")

def stage_5():
    print("  -----")
    print("  |   |")
    print("  O   |")
    print(" ---  |")
    print("/ | \ |")
    print("  |   |")
    print(" ---  |")
    print("      |")
    print("      |")
    print("      |")
    print("-------")

def stage_6():
    print("  -----")
    print("  |   |")
    print("  O   |")
    print(" ---  |")
    print("/ | \ |")
    print("  |   |")
    print(" ---  |")
    print("/   \ |")
    print("      |")
    print("      |")
    print("-------")

def stage_7():
    print("  -----")
    print("  |   |")
    print("  O   |")
    print(" ---  |")
    print("/ | \ |")
    print("  |   |")
    print(" ---  |")
    print("/   \ |")
    print("|   | |")
    print("      |")
    print("-------")